# -*- coding: utf-8 -*-
"""Data preparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KCz3yHLJq8L30LNZM0msNhsDEPfjWTSW
"""

#Identify the last line where the player loses possession of the ball
Data['Episode']=0
t=1
Data.loc[0, 'Episode']=1
for i in range(1, len(Data)):
  if Data.loc[i, 'team_id']==Data.loc[i-1, 'team_id']:
    Data.loc[i, 'Episode']=t
  else:
    t+=1
    Data.loc[i, 'Episode']=t

# Reward
Data['Reward']=0
for i in range(0, len(Data)):
  if (Data.loc[i, 'result_id']==1 and Data.loc[i, 'type_id']==11):
    Data.loc[i, 'Reward']=1
  elif (Data.loc[i, 'result_id']!=1 and Data.loc[i, 'type_id']==11):
    Data.loc[i, 'Reward']=0
  elif (Data.loc[i, 'result_id']==1 and Data.loc[i, 'type_id']!=11):
    Data.loc[i, 'Reward']=0
  else:
    Data.loc[i, 'Reward']=-1

Data['episode'] = Data['Episode'].diff()

np.unique(Data['type_id'])

Data_filtered = Data[Data['episode'] != 0]

# END LIST FOR Train
End_list= Data.index[(Data['episode'] !=0) ].tolist()

# All Possession
def possession_list_maker(Data, End_list):
    all_possessions=[]
    for delays in range(0,len(End_list)):
        possession=[]
        df= Data.iloc[End_list[delays-1]+1:End_list[delays]+1]
        pos= df.to_numpy()
        all_possessions.append(pos)
    return all_possessions

all_possessions = possession_list_maker(Data, End_list)

all_possessions=np.array(all_possessions)